Running:
  cons: '4000'
  during: '10'
  epoch: '1'
  interval: '2'
  savepath: ./logs/
Setting:
  cuda_devices: '0'
  dt: '0.01'
  platform: null
planar_topology:
  N: '2000'
  cell_prob: 0.5, 0.3, 0.15, 0.05
  cell_scale: 1, 3, 5, 7
  cell_unit: '0.00497'
  connect_len: '0.3'
  draw_3D_face: false
  draw_connet: false
  draw_point: true
  ele_scale: '0.35'
  far_n: '2'
  fire_n: '30000'
  lateral_inh: false
  near_p: '0.0008'
  savepath: ./logs/outcomes/
  unit: '1'
real_world_data:
  draw_ori: false
  draw_p: false
  response: ./data/brain_spike/2.1.mat
  savepath: ./logs/outcomes/
  stimulus: null
synapses:
  dy_delete: true
  homeo_type: norm
  multiple: 0, 3
  neuron_type: null
  plasticity_type: null
  stdp:
    A1: '1'
    A2: '1'
    method: exp_auto
    tau_s: '40'
    tau_t: '40'
    theta_n: '0.001'
    theta_p: '0.001'
  stp:
    U: '0.2'
    tau_d: '2'
    tau_f: '2'
  synapses_type: null
  w_bound: '1'
